### ISSUE TITLE
Missing self-loops in dataset loader?

### ISSUE THREAD

**Issue by tsafavi** [MPeti01/wikipedia-gnns#4]
Hi again! I noticed in the Appendix of your paper that you reported the evaluation as being performed with self-loops added to the graph. However, in the `from_file` data loading function of `experiments/node_classification/load_graph_data.py`, I don't believe self-loops are being added anywhere. 

To verify, I added the following 3 lines between [line 52 and 53](https://github.com/pmernyei/wiki-cs-dataset/blob/4078c80e698c58e5cfb3ef19f2716f1032dced4d/experiments/node_classification/load_graph_data.py#L52) of `load_graph_data.py`:
```
import dgl
g = dgl.remove_self_loop(g)
g = dgl.add_self_loop(g)
```

Using the same hyperparameters as what was provided in the README, I get an average accuracy of 79.08% for GCN.

**Comment by pmernyei** [comment]
Hi! You seem to be quite right unfortunately - I am very sorry for such an embarrassing mistake. I promise to update the repo and the paper around September, I am quite busy for the moment.

**Comment by pmernyei** [comment]
Fixed the data loader in the repo [here](https://github.com/pmernyei/wiki-cs-dataset/commit/f5207315d649377f936edb66d7d93f5342f01d81). I will rerun the benchmarks in the next few days and update the paper accordingly. Unfortunately I don't currently have access to resources where I could do the hyperparameter tuning again, but I will at least rerun with the same parameters.

**Comment by pmernyei** [comment]
Uploaded new results to Arxiv, due to appear on Tuesday 11th. Only GCN and GAT ended up benefitting from self-loops, their new results are:

- GCN: 	79.07% +- 0.10%
- GAT:	79.63% +- 0.10%
