### ISSUE TITLE
Is Wiki-CS a directed graph benchmark?

### ISSUE THREAD

**Issue by hazdzz** [MPeti01/wikipedia-gnns#5]
I'm studying at Graph Neural Networks for directed graphs. Is Wiki-CS a directed graph benchmark?

**Comment by pmernyei** [comment]
It was originally intended to be a directed benchmark, and I ran the experiments accordingly using the DGL library, but I mistakenly forgot to process it appropriately when loading for Pytorch Geometric. So it looks like most users actually worked with it in directed form (most unknowingly, although some seem to have noticed). I've updated the repo to have an optional flag in the Pytorch data loader (defaulting to undirected) in [this commit](https://github.com/pmernyei/wiki-cs-dataset/commit/f5207315d649377f936edb66d7d93f5342f01d81), and opened a [PR for Pytorch Geometric](https://github.com/pyg-team/pytorch_geometric/pull/3796) to do the same there. Let me know if anything's unclear!
