### ISSUE TITLE
Why 297110 edges？

### ISSUE THREAD

**Issue by MarchenCreator** [MPeti01/wikipedia-gnns#7]
thx，but I parsed the raw data and obtained 297,110 edges. However, the dataset description seems to indicate there are 216,123?

**Comment by 1didi** [comment]
I have the same question！

**Comment by 1didi** [comment]
> thx，but I parsed the raw data and obtained 297,110 edges. However, the dataset description seems to indicate there are 216,123?

I'm sorry I didn't read it carefully. This question has already been answered, in closed issue.
